Problem-1

In [ ]:
#task-1
import numpy as np
empty_arr = np.zeros((2,2))
print(empty_arr)

[[0. 0.]
 [0. 0.]]


In [ ]:
#task-2
import numpy as np
empty_Arr2=np.ones((4,2))
print(empty_Arr2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#task-3
array_full=np.full(2,2)
print(array_full)

[2 2]


In [ ]:
#task-4
zeros_arr= np.zeros([2,2])
print(zeros_arr)

[[0. 0.]
 [0. 0.]]


In [ ]:
#task-5
ones_Arr=np.ones([2,2])
print(ones_Arr)

[[1. 1.]
 [1. 1.]]


In [ ]:
#task-6
new_list=[1,2,3,4]
array = np.array(new_list)
print(array)

[1 2 3 4]


Problem-2


In [ ]:
#task-1
array_2 = np.arange(10,50)
print(array_2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#task-2
array_3 = np.array([0,1,2,3,4,5,6,7,8])
new = array_3.reshape(3,3)
print(new)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#task-3
identity = np.eye(3,3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#task-4
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random array:", random_array)
print("Mean of the array:", mean_value)




Random array: [0.92537191 0.55077728 0.49926166 0.97322439 0.45945455 0.68825131
 0.74785877 0.41026036 0.31056624 0.97427489 0.49674761 0.58628571
 0.70649761 0.60339744 0.01295425 0.34390555 0.11239129 0.84319158
 0.27390142 0.78498754 0.50903619 0.56719617 0.64481974 0.56876419
 0.52980764 0.3911568  0.82262047 0.02286523 0.17028868 0.76449433]
Mean of the array: 0.5431536936620108


In [ ]:
#task-5
import numpy as np
random_array = np.random.random((10, 10))
min_value = np.min(random_array)
max_value = np.max(random_array)
print("Random Array:")
print(random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)


Random Array:
[[0.83962334 0.66191602 0.95517587 0.46552761 0.97887204 0.05506961
  0.06005185 0.1886684  0.12148598 0.65860764]
 [0.31648789 0.94314273 0.29431442 0.36460548 0.17489188 0.88296782
  0.06141768 0.9897901  0.68757451 0.05782267]
 [0.62177141 0.96887453 0.85102654 0.94851092 0.73731809 0.95985988
  0.61271839 0.18657882 0.77732475 0.46367606]
 [0.28962702 0.4921087  0.52627671 0.53557947 0.12502041 0.48165442
  0.83691277 0.81353178 0.1389005  0.43138839]
 [0.96206503 0.3579496  0.40968349 0.74197187 0.43055488 0.04790261
  0.54421568 0.62518261 0.51994751 0.59614622]
 [0.02858386 0.07284657 0.08801905 0.91573761 0.29722977 0.95441995
  0.57155517 0.55356883 0.50067661 0.20546287]
 [0.43088408 0.64620171 0.02484465 0.39628428 0.21266273 0.77992924
  0.55962475 0.03179497 0.91127927 0.27504755]
 [0.6365395  0.18403907 0.82898333 0.41942787 0.40180417 0.20368554
  0.36421347 0.2737159  0.80923349 0.01547548]
 [0.28690635 0.97552464 0.3347515  0.05692012 0.90906987 0.2824858

In [ ]:
#task-5
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#task-6
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)


[0 4 0 0 2 1]


In [ ]:
#task-7
array_6 = np.array([[1,0,0,0]])
print(array_6)

[[1 0 0 0]]


Task-8


In [ ]:
# prompt: Create a 2d array with 1 on border and 0 inside.

import numpy as np

def create_border_array(rows, cols):
  """Creates a 2D array with 1s on the border and 0s inside.

  Args:
    rows: The number of rows in the array.
    cols: The number of columns in the array.

  Returns:
    A NumPy array with the specified dimensions and border.
  """

  arr = np.zeros((rows, cols), dtype=int)
  arr[0, :] = 1  # Top row
  arr[-1, :] = 1  # Bottom row
  arr[:, 0] = 1  # Left column
  arr[:, -1] = 1  # Right column
  return arr

# Example usage:
rows = 3
cols = 3
result_array = create_border_array(rows, cols)
result_array

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

task-9

Problem-3


In [ ]:


x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Task-1
add = x + y
add2 = w + v
print("Addition1:\n", add)
print("Addition2:\n", add2)

#Task-2

sub = x-y
sub2= w-v
print("Subtraction1:\n", sub)
print("Subtraction2:\n", sub2)


#Task-3
new_x = x*2
new_y = y*3
new_v = v*4
new_w = w*5
print("X:\n", new_x)
print("Y:\n", new_y)
print("V:\n", new_v)
print("Z:\n", new_w)

#Task-4
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
sqrt_x = np.sqrt(x)
sqrt_y = np.sqrt(y)
sqrt_v = np.sqrt(v)
sqrt_w = np.sqrt(w)

print("Square root of x:\n", sqrt_x)
print("Square root of y:\n", sqrt_y)
print("Square root of v:\n", sqrt_v)
print("Square root of w:\n", sqrt_w)

#Task-5
dot_v_w=np.dot(v,w)
dot_x_v=np.dot(x,v)
dot_x_y=np.dot(x,y)
print("Dot product of v and w arrays:\n", dot_v_w)
print("Dot product of x and v arrays:\n", dot_x_v)
print("Dot product of x and y arrays:\n", dot_x_y)

#Task-6

array_v_w = np.stack((v, w), axis=0)
print("Stacked v and w arrays:\n", array_v_w)


array_x_y = np.vstack((x, y))
print("Stacked x and y arrays (vertically):\n", array_x_y)

#Task-7
array_x_v=np.vstack((x,v))
print("Stacked x and v arrays (vertically):\n", array_x_v)
#array_x_v=np.hstack((x,v))





Addition1:
 [[ 6  8]
 [10 13]]
Addition2:
 [20 22]
Subtraction1:
 [[-4 -4]
 [-4 -3]]
Subtraction2:
 [2 2]
X:
 [[ 2  4]
 [ 6 10]]
Y:
 [[15 18]
 [21 24]]
V:
 [36 40]
Z:
 [55 60]
Square root of x:
 [[1.         1.41421356]
 [1.73205081 2.23606798]]
Square root of y:
 [[2.23606798 2.44948974]
 [2.64575131 2.82842712]]
Square root of v:
 [3.         3.16227766]
Square root of w:
 [3.31662479 3.46410162]
Dot product of v and w arrays:
 219
Dot product of x and v arrays:
 [29 77]
Dot product of x and y arrays:
 [[19 22]
 [50 58]]
Stacked v and w arrays:
 [[ 9 10]
 [11 12]]
Stacked x and y arrays (vertically):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Stacked x and v arrays (vertically):
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


Problem-4

In [ ]:
#Task-1

import numpy as np

A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
print("A * A_inv = \n", result)
I = np.eye(2)
print("\nIdentity matrix I:\n", I)
print("\nIs A * A_inv approximately equal to I? ", np.allclose(result, I))


#task-2
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB = \n", AB)
print("\nBA = \n", BA)
print("\nIs AB equal to BA? ", np.array_equal(AB, BA))

#task-3
transpose_AB= AB.transpose()
print("(AB)T =\n",transpose_AB)

transpose_B= B.transpose()
transpose_A= A.transpose()
AB_transpose= np.dot(transpose_B,transpose_A)
print("(B)T(A)T =\n",AB_transpose)
print("\nIs (AB)T equal to (B)t(A)t? ", np.array_equal(transpose_AB, AB_transpose))





A * A_inv = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Identity matrix I:
 [[1. 0.]
 [0. 1.]]

Is A * A_inv approximately equal to I?  True
AB = 
 [[23 13]
 [51 29]]

BA = 
 [[36 44]
 [13 16]]

Is AB equal to BA?  False
(AB)T =
 [[23 51]
 [13 29]]
(B)T(A)T =
 [[23 51]
 [13 29]]

Is (AB)T equal to (B)t(A)t?  True


In [ ]:
#Solve Linear methods
import numpy as np
A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B = np.array([-1,-3,9])
A_inv = np.linalg.inv(A)
A_muls_B = np.dot(A_inv,B)
print("Value of X,Y and Z are = \n",A_muls_B)




Experiment Qn-4.2

In [ ]:
#using time.time()
import time
import numpy as np

# Create two lists of size 1,000,000
size = 1_000_000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]
start_time_list = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end_time_list = time.time()
time_list = end_time_list - start_time_list

print(f"Time taken for element-wise addition using Python lists: {end_time_list - start_time_list:.6f} seconds")

array1 = np.arange(size)
array2 = np.arange(size)

start_time_numpy = time.time()
result_array = array1 + array2
end_time_numpy = time.time()
time_numpy = end_time_numpy - start_time_numpy


print(f"Time taken for element-wise addition using NumPy arrays: {end_time_numpy - start_time_numpy:.6f} seconds")





Time taken for element-wise addition using Python lists: 0.167946 seconds
Time taken for element-wise addition using NumPy arrays: 0.004653 seconds


In [ ]:
import time
import numpy as np
size = 1_000_000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]
start_time_list = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end_time_list = time.time()
time_list = end_time_list - start_time_list
print(f"Time taken for element-wise multiplication using Python lists: {time_list:.6f} seconds")
array1 = np.arange(size)
array2 = np.arange(size)
start_time_numpy = time.time()
result_array = array1 * array2
end_time_numpy = time.time()
time_numpy = end_time_numpy - start_time_numpy
print(f"Time taken for element-wise multiplication using NumPy arrays: {time_numpy:.6f} seconds")


Time taken for element-wise multiplication using Python lists: 0.169059 seconds
Time taken for element-wise multiplication using NumPy arrays: 0.002747 seconds


In [ ]:
import time
import numpy as np

size = 1_000_000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

start_time_list = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time_list = time.time()
time_list = end_time_list - start_time_list
print(f"Time taken for dot product using Python lists: {time_list:.6f} seconds")

array1 = np.arange(size)
array2 = np.arange(size)

start_time_numpy = time.time()
dot_product_numpy = np.dot(array1, array2)
end_time_numpy = time.time()
time_numpy = end_time_numpy - start_time_numpy
print(f"Time taken for dot product using NumPy arrays: {time_numpy:.6f} seconds")




Time taken for dot product using Python lists: 0.165247 seconds
Time taken for dot product using NumPy arrays: 0.001653 seconds


In [ ]:
import time
import numpy as np

size = 1000
matrix1 = [[i for i in range(size)] for _ in range(size)]
matrix2 = [[i for i in range(size)] for _ in range(size)]

start_time_list = time.time()
result_list = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(size)) for j in range(size)] for i in range(size)]
end_time_list = time.time()
time_list = end_time_list - start_time_list
print(f"Time taken for matrix multiplication using Python lists: {time_list:.6f} seconds")

array1 = np.arange(size * size).reshape(size, size)
array2 = np.arange(size * size).reshape(size, size)

start_time_numpy = time.time()
result_array = np.dot(array1, array2)  
end_time_numpy = time.time()

print(f"Time taken for matrix multiplication using NumPy arrays: {time_numpy:.6f} seconds")



Time taken for matrix multiplication using Python lists: 223.348025 seconds
Time taken for matrix multiplication using NumPy arrays: 0.005856 seconds
